OPENAI_API_KEY="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"
SF_USER='PRAKASH3105'
SF_PASSWORD='PrisonBreak@1'
SF_ACCOUNT='ejdbkav-ix82585'
SF_WAREHOUSE='COMPUTE_WH'
SF_DATABASE = 'SNOWFLAKE_SAMPLE_DATA'
SF_SCHEMA = 'TPCH_SF1'
SF_ROLE='ACCOUNTADMIN'
