OPENAI_API_KEY="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"
SF_USER='PRAKASH3105'
SF_PASSWORD='PrisonBreak@1'
SF_ACCOUNT='ejdbkav-ix82585'
SF_WAREHOUSE='COMPUTE_WH'
SF_DATABASE = 'SNOWFLAKE_SAMPLE_DATA'
SF_SCHEMA = 'TPCH_SF1'
SF_ROLE='ACCOUNTADMIN'
