OPENAI_API_KEY="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"
SF_USER='PRAKASH3105'
SF_PASSWORD='PrisonBreak@1'
SF_ACCOUNT='ejdbkav-ix82585'
SF_WAREHOUSE='COMPUTE_WH'
SF_DATABASE = 'SNOWFLAKE_SAMPLE_DATA'
SF_SCHEMA = 'TPCH_SF1'
SF_ROLE='ACCOUNTADMIN'
